name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  python-ci:
    uses: m0nklabs/github-action-runners/.github/workflows/python-ci.yml@main
    with:
      python-version: "3.12"
      src-dir: app
      test-dir: tests
      lint-path: "app scripts tests"
    secrets: inherit
